name: Build/release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project (macOS)
        run: npm run dist:m

      - name: Upload dmg
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'build/*.dmg'

      - name: Upload latest.yml
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'build/latest.yml'

  build_on_win:
    runs-on: windows-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project (Windows)
        run: npm run dist:w

      - name: Upload .exe
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'build/*.exe'

      - name: Upload .msi
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'build/*.msi'

  build_on_linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project (Linux)
        run: npm run dist:l

      - name: Upload AppImage
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'build/*.AppImage'

      - name: Upload .deb
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'build/*.deb'
